# Default configuration for Adaptive RL Agent
# This file contains default hyperparameters and settings

# Environment Configuration
environment:
  name: "DynamicTrafficEnv"
  max_steps: 1000
  render_mode: null
  
  # Service types and their properties
  services:
    - name: "video"
      base_demand: 50.0
      volatility: 0.3
    - name: "gaming"
      base_demand: 30.0
      volatility: 0.5
    - name: "downloads"
      base_demand: 40.0
      volatility: 0.2
    - name: "browsing"
      base_demand: 20.0
      volatility: 0.4

# Agent Configuration
agent:
  # Network architecture
  hidden_layers: [128, 128]
  activation: "relu"
  
  # Training hyperparameters
  learning_rate: 0.0005
  batch_size: 64
  buffer_size: 100000
  gamma: 0.99
  tau: 0.001
  update_every: 4
  
  # Exploration parameters
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  
  # Device settings
  device: "auto"  # "auto", "cpu", "cuda"
  seed: 42

# Training Configuration
training:
  episodes: 2000
  max_steps_per_episode: 1000
  target_score: 200.0
  save_every: 500
  log_every: 100
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 200
    min_improvement: 1.0

# Evaluation Configuration
evaluation:
  episodes: 100
  render: false
  save_results: true
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/training.log"
  
# Paths Configuration
paths:
  models: "models/"
  data: "data/"
  logs: "logs/"
  results: "results/"
  
# Visualization Configuration
visualization:
  save_plots: true
  show_plots: false
  plot_format: "png"
  dpi: 300 